query documentsQuery {
  documents {
      id
      title
      created
  }
}

query notificationsQuery {
  notifications {
    id
    title
    created
    content
  }
}

query markersQuery {
  markers {
    id
    type
    created
  }
}

mutation seedMutation {
  seed
}
