query documentsQuery {
  documents {
    id
    title
    created
  }
}

query notificationsQuery {
  notifications {
    id
    title
    created
  }
}

query markersQuery {
  markers {
    id
    type
    created
  }
}

query photoFoldersQuery {
  photoFolders
}

query photosByFolderQuery($folder:String!) {
  photos(where: {folder:{
    eq: $folder
  }}) {
    nodes {
      id
      path
      caption
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
      startCursor
    }
  }
}

query photosQuery{
  photos {
    nodes {
      id
      path
      caption
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
      startCursor
    }
  }
}